on:
  push:
    branches:
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Text
        run: |
          cd Hotel
          xcodebuild clean build test -project Hotel.xcodeproj -scheme Hotel -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: 'platform=iOS Simulator,OS=13.5,name=iPhone SE'
#       - name: Update Code Coverage
#         run: |
#           bash <(curl -s https://codecov.io/bash) -J 'Texstyle'
#       - name: Update docs
#         run: |
#           gem install jazzy
#           jazzy
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git commit -m "Update docs" -a
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
